### ISSUE TITLE
[Bubble] Caught error: DiscordAPIError: cannot send an empty message

### ISSUE THREAD

**Issue by MarcinOfficial** [Titon191/bubble-engine#1]
I am getting this error when I am trying to send an embed.

**Comment by Titon191** [comment]
Hi @MarcinOfficial,
Thank you for submitting this issue.
This error is probably because you have installed discord.js **v14 or highier**. Latest Bubble Engine (1.1.5) is using discord.js **v.12.5.3** - we will rewrite this package to latest discord.js as soon as possible, but now please try installing older discord.js version using `npm install discord.js@12.5.3`.
